meta:
  engine: 4.1.0
# U is a predefined unit of measure that means 19.05mm, which is MX spacing (u is 19.00mm)
points:
  zones:
    matrix:
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        xtra_pinky:
          rows:
            top:
              skip: true
        pinky.key.stagger: -0.2U
        ring.key.stagger: 0.8U
        middle.key.stagger: 0.25U
        index.key.stagger: -0.3U
        inner.key.stagger: -0.15U
      rows:
        bottom.padding: U
        home.padding: U
        top.padding: U
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [1.6U, -1.8U]
      columns:
        tucky:
          key.splay: -20
          rows:
            top:
              key.name: thumb_tucky_high
            bottom:
              key.name: thumb_tucky_low
        middle:
          key.spread: U
          key.splay: -15
          key.origin: [-0.5U, -0.5U]
          rows:
            top:
              key.name: thumb_middle_high
            bottom:
              key.name: thumb_middle_low
        reachy:
          key.spread: U
          key.splay: -15
          key.origin: [-0.5U, -0.5U]
          rows:
            top:
              key.name: thumb_reachy_low
            bottom:
              skip: true
    hardware:
      anchor:
        ref: thumb_tucky_top
      columns:
        stick_pos:
          key:
            shift: [-1.2U, 0]
            rotate: 20
            mirror: false
            asym: left
  mirror:
    ref: matrix_pinky_home
    distance: 300

pcbs:
  gnocchi:
    template: kicad8
    footprints:
      keys:
        what: ceoloide/switch_mx
        where: true
        params:
          from: GND
          to: "{{name}}"
          reversible: true
          solder: true
          include_keycap: true
      joystick:
        what: joystick
        where: hardware_stick_pos_mirror
        asym: source
        params:
          X: P026
          Y: P027
      wheel:
        what: evqwgd001
        where: hardware_stick_pos
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          A: P029
          B: GND
          C: P031
          D: undef
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          - ref: matrix_inner_home
            shift: [1U, 0.5U]
        params:
          reversible: true
          only_required_jumpers: true
          P7: matrix_pinky_top
          P7_label: P7
          P18: matrix_ring_top
          P18_label: P18
          P19: matrix_middle_top
          P19_label: P19
          P20: matrix_index_top
          P20_label: P20
          P21: matrix_inner_top
          P21_label: P21
          P15: matrix_pinky_home
          P15_label: P15
          P14: matrix_ring_home
          P14_label: P14
          P16: matrix_middle_home
          P16_label: P16
          P10: matrix_index_home
          P10_label: P10
          P1: matrix_inner_home
          P1_label: P1
          P2: matrix_pinky_bottom
          P2_label: P2
          P3: matrix_ring_bottom
          P3_label: P3
          P4: matrix_middle_bottom
          P4_label: P4
          P5: matrix_index_bottom
          P5_label: P5
          P6: matrix_inner_bottom
          P6_label: P6
          P8: thumb_tucky
          P8_label: P8
          P9: thumb_reachy
          P9_label: P9
