meta:
  engine: 4.1.0
# U is a predefined unit of measure that means 19.05mm, which is MX spacing (u is 19.00mm)
points:
  zones:
    matrix:
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        xtra_pinky:
          key:
            column_net: P113
          rows:
            top:
              skip: true
        pinky:
          key:
            column_net: P111
            stagger: -0.2U
        ring:
          key:
            column_net: P010
            stagger: 0.8U
        middle:
          key:
            column_net: P009
            stagger: 0.25U
        index:
          key:
            column_net: P106
            stagger: -0.3U
        inner:
          key:
            column_net: P104
            stagger: -0.15U
      rows:
        bottom:
          row_net: P031
          padding: U
        home:
          row_net: P029
          padding: U
        top:
          row_net: P002
          padding: U

    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [1.8U, -1.8U]
      columns:
        tucky:
          key.splay: -20
          rows:
            top:
              key.name: thumb_tucky_high
            bottom:
              key.name: thumb_tucky_low
        middle:
          key.spread: U
          key.splay: -15
          key.origin: [-0.5U, -0.5U]
          rows:
            top:
              key.name: thumb_middle_high
            bottom:
              key.name: thumb_middle_low
        reachy:
          key.spread: U
          key.splay: -15
          key.origin: [-0.5U, -0.5U]
          rows:
            top:
              key.name: thumb_reachy_low
            bottom:
              skip: true
      rows:
        top:
          row_net: P011
        bottom:
          row_net: P115

    hardware:
      anchor:
        ref: thumb_tucky_top
        shift: [-1.2U, 0]
        rotate: 20

    controllers:
      anchor:
        ref: matrix_inner_home
        shift: [1U, 0.5U]
      columns:
        main:
          key:
            tags: [mcu]

  mirror:
    ref: matrix_pinky_home
    distance: 300

outlines:
  left_raw:
    - what: rectangle
      where: /^matrix_|^thumb_/
      size: [1U + 2, 1U + 2]
    - what: rectangle
      where: /^controllers_main_key/
      size: [18, 33]

  right_raw:
    - what: rectangle
      where: /^mirror_/
      size: [1U + 2, 1U + 2]

  left_outline:
    - what: outline
      name: left_raw
      expand: 3
      fillet: 2

  right_outline:
    - what: outline
      name: right_raw
      expand: 3
      fillet: 2

pcbs:
  left_gnocchi:
    template: kicad8
    outlines:
      main:
        outline: left_outline

    footprints:
      keys:
        what: ceoloide/switch_mx
        where: /^matrix_|^thumb_/
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          hotswap: true
          reversible: false
          solder: false
          include_keycap: true

      joystick:
        what: joystick
        where: hardware
        asym: left
        params:
          H1: GND
          H2: P020
          H3: VCC
          V1: GND
          V2: P022
          V3: VCC
          B1A: pos
          B2A: GND
          B1B: GND
          B2B: GND
          MOUN: GND

      mcu:
        what: ceoloide/mcu_nice_nano
        where: controllers_main_key
        params:
          reversible: true
          only_required_jumpers: true

  right_gnocchi:
    template: kicad8
    outlines:
      main:
        outline: right_outline

    footprints:
      keys:
        what: ceoloide/switch_mx
        where: /^mirror_/
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          hotswap: true
          reversible: false
          solder: false
          include_keycap: true

      wheel:
        what: evqwgd001
        where: hardware
        asym: right
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          A: P029
          B: GND
          C: P031
          D: undef
