meta:
  engine: 4.1.0
# U is a predefined unit of measure that means 19.05mm, which is MX spacing (u is 19.00mm)
points:
  zones:
    matrix:
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        pinky:
          key:
            column_net: P2
            stagger: -0.2U
        ring:
          key:
            column_net: P3
            stagger: 0.8U
        middle:
          key:
            column_net: P4
            stagger: 0.25U
        index:
          key:
            column_net: P5
            stagger: -0.3U
        inner:
          key:
            column_net: P6
            stagger: -0.15U
      rows:
        bottom:
          row_net: P7
          padding: U
        home:
          row_net: P8
          padding: U
        top:
          row_net: P9
          padding: U

    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [1.8U, -1.8U]
      columns:
        tucky:
          key.splay: -20
          rows:
            top:
              key.name: thumb_tucky_high
            bottom:
              key.name: thumb_tucky_low
        mid:
          key.spread: U
          key.splay: -15
          key.origin: [-0.5U, -0.5U]
          rows:
            top:
              key.name: thumb_mid_high
            bottom:
              key.name: thumb_mid_low
        reachy:
          key.spread: U
          key.splay: -15
          key.origin: [-0.5U, -0.5U]
          rows:
            top:
              key.name: thumb_reachy_low
            bottom:
              skip: true
      rows:
        top:
          row_net: P10
        bottom:
          row_net: P16

    hardware:
      anchor:
        ref: thumb_tucky_top
        shift: [-1.2U, 0]
        rotate: 20
      columns:
        main:
          key:
            tags: [hardware]

    controllers:
      anchor:
        ref: matrix_inner_home
        shift: [1U, 0.6U]
      columns:
        main:
          key:
            tags: [mcu]
            asym: left

  mirror:
    ref: matrix_pinky_home
    distance: 300

outlines:
  left_raw:
    - what: rectangle
      where: /^matrix_|^thumb_|^hardware_/
      size: [1U + 2, 1U + 2]

    - what: rectangle
      where: /^controllers_/
      size: [18, 33]

  right_raw:
    - what: rectangle
      where: /^mirror_/
      size: [1U + 2, 1U + 2]

  left_outline:
    - what: outline
      name: left_raw
      expand: 3
      fillet: 2
      bound: true

  right_outline:
    - what: outline
      name: right_raw
      expand: 3
      fillet: 2
      bound: true

pcbs:
  left_gnocchi:
    template: kicad8
    outlines:
      main:
        outline: left_outline

    footprints:
      keys:
        what: ceoloide/switch_mx
        where: /^matrix_|^thumb_/
        params:
          from: "{{row}}"
          to: "{{colrow}}"
          hotswap: true
          reversible: false
          solder: false
          include_keycap: true

      joystick:
        what: joystick
        where: /^hardware_/
        params:
          H1: GND
          H2: P14
          H3: VCC
          V1: GND
          V2: P15
          V3: VCC
          B1A: P20
          B2A: GND
          B1B: GND
          B2B: GND
          MOUN: GND

      mcu:
        what: ceoloide/mcu_nice_nano
        where: /^controllers_/
        params:
          reversible: false

      diodes:
        what: diode
        where: /^matrix_|^thumb_/
        adjust:
          shift: [0, -4.5]
          rotate: 0
        params:
          from: "{{colrow}}"
          to: "{{row}}"

  right_gnocchi:
    template: kicad8
    outlines:
      main:
        outline: right_outline

    footprints:
      keys:
        what: ceoloide/switch_mx
        where: /^mirror_/
        params:
          from: "{{row}}"
          to: "{{colrow}}"
          hotswap: true
          reversible: false
          solder: false
          include_keycap: true

      wheel:
        what: evqwgd001
        where: /^mirror_hardware_/
        params:
          from: "{{row}}"
          to: "{{colrow}}"
          A: P19
          B: GND
          C: P18
          D: undef

      wheel_d:
        what: diode
        where: /^mirror_hardware_/
        adjust:
          shift: [0, -6]
        params:
          from: "{{colrow}}"
          to: "{{row}}"

      diodes:
        what: diode
        where: /^mirror_/
        adjust:
          shift: [0, -4.5]
          rotate: 0
        params:
          from: "{{colrow}}"
          to: "{{row}}"

      via_col:
        what: via
        where: /^mirror_via/
        params:
          net: "{{column_net}}"

      via_row:
        what: via
        where: /^mirror_via/
        params:
          net: "{{colrow}}"
